config/routes.rb
Rails.application.routes.draw do
  
  get 'bmi/index'
  get "bmi", to: "bmi#index"
  post "bmi/result", to: "bmi#result"
  #get "/posts", to: "posts#index"
  #get "/posts/:id", to: "posts#show"

  #get "/users", to: redirect('https://www.google.com')
  get "/users", to: "users#index"
  get "/hello_world", to: "pages#hello"

  resources :post2s
  resources :posts
  resources :users


  





  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/post2.rb
class Post2 < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bmi_controller.rb
class BmiController < ApplicationController
  def index
  end

  def result
    height = params[:body_height].to_f/100
    weight = params[:body_weight].to_f

    #formula: BMI = weight/shengao pingfang
    @bmi=(weight/(height*height)).round(2)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def hello
     #   render html:"<h1>Hello , you world!</h1>".html_safe+"<h1>I'm a ET from very far away.</h1>".html_safe
    render json: params["name"]

    end
end

app/controllers/post2s_controller.rb
class Post2sController < ApplicationController
  before_action :set_post2, only: [:show, :edit, :update, :destroy]

  # GET /post2s
  # GET /post2s.json
  def index
    @post2s = Post2.all
  end

  # GET /post2s/1
  # GET /post2s/1.json
  def show
  end

  # GET /post2s/new
  def new
    @post2 = Post2.new
  end

  # GET /post2s/1/edit
  def edit
  end

  # POST /post2s
  # POST /post2s.json
  def create
    @post2 = Post2.new(post2_params)

    respond_to do |format|
      if @post2.save
        format.html { redirect_to @post2, notice: 'Post2 was successfully created.' }
        format.json { render :show, status: :created, location: @post2 }
      else
        format.html { render :new }
        format.json { render json: @post2.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /post2s/1
  # PATCH/PUT /post2s/1.json
  def update
    respond_to do |format|
      if @post2.update(post2_params)
        format.html { redirect_to @post2, notice: 'Post2 was successfully updated.' }
        format.json { render :show, status: :ok, location: @post2 }
      else
        format.html { render :edit }
        format.json { render json: @post2.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /post2s/1
  # DELETE /post2s/1.json
  def destroy
    @post2.destroy
    respond_to do |format|
      format.html { redirect_to post2s_url, notice: 'Post2 was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post2
      @post2 = Post2.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post2_params
      params.require(:post2).permit(:title, :content, :is_available, :user)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :is_available, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :tel)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bmi_helper.rb
module BmiHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/post2s_helper.rb
module Post2sHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bmi/index.html.erb
<h1>BMI CALCULATER</h1>
<h1>
<%= form_tag '/bmi/result' do  %>

    HEIGHT我的身高: <%=text_field_tag 'body_height'  %>单位: 厘米 cm<br />

    WEIGHT我的体重: <%=text_field_tag 'body_weight'  %>单位: 千克 kg<br />

    <%=submit_tag "START 计算"%>

    <%=button_tag 'Reset', type:'reset', disabled:false%>
<h1>
<% end %>

app/views/bmi/result.html.erb
<h1> Your BMI Value is:<%= @bmi %>  <h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tt</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :is_available %>
    <%= form.check_box :is_available %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/pages/hello.html.erb
<h1>Hello, you guys!  U see this through View.</h1>


<h2>I'm a designer, I can see it also. This is for you...</h2>

app/views/pages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Is available</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= post.is_available %></td>
        <td><%= post.user.name %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/pages/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p>
  <strong>Is available:</strong>
  <%= @post.is_available %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user_id %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/post2s/_form.html.erb
<%= form_with(model: post2, local: true) do |form| %>
  <% if post2.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post2.errors.count, "error") %> prohibited this post2 from being saved:</h2>

      <ul>
        <% post2.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :is_available %>
    <%= form.check_box :is_available %>
  </div>

  <div class="field">
    <%= form.label :user %>
    <%= form.text_field :user %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/post2s/edit.html.erb
<h1>Editing Post2</h1>

<%= render 'form', post2: @post2 %>

<%= link_to 'Show', @post2 %> |
<%= link_to 'Back', post2s_path %>

app/views/post2s/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Post2s</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Is available</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @post2s.each do |post2| %>
      <tr>
        <td><%= post2.title %></td>
        <td><%= post2.content %></td>
        <td><%= post2.is_available %></td>
        <td><%= post2.user %></td>
        <td><%= link_to 'Show', post2 %></td>
        <td><%= link_to 'Edit', edit_post2_path(post2) %></td>
        <td><%= link_to 'Destroy', post2, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post2', new_post2_path %>

app/views/post2s/new.html.erb
<h1>New Post2</h1>

<%= render 'form', post2: @post2 %>

<%= link_to 'Back', post2s_path %>

app/views/post2s/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post2.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post2.content %>
</p>

<p>
  <strong>Is available:</strong>
  <%= @post2.is_available %>
</p>

<p>
  <strong>User:</strong>
  <%= @post2.user %>
</p>

<%= link_to 'Edit', edit_post2_path(@post2) %> |
<%= link_to 'Back', post2s_path %>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :is_available %>
    <%= form.check_box :is_available %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Is available</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= post.is_available %></td>
        <td><%= post.user.name %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p>
  <strong>Is available:</strong>
  <%= @post.is_available %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user_id %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :tel %>
    <%= form.text_field :tel %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Tel</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.tel %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Tel:</strong>
  <%= @user.tel %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>